#include <stdio.h>

/* Each new term in the Fibonacci sequence is generated by adding the previous two terms. */
/*    By starting with 1 and 2, the first 10 terms will be: */
/*      1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...  */
/*          By considering the terms in the Fibonacci sequence whose values do not exceed four million, */
/*            find the sum of the even-valued terms.  */
/* フィボナッチ数列の項は前の2つの項の和である. 最初の2項を 1, 2 とすれば, 最初の10項は以下の通りである. */
/*     1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ... */
/*     数列の項の値が400万より小さい, 偶数値の項の総和を求めよ. */
/*     Note:この問題は最近更新されました. お使いのパラメータが正しいかどうか確認してください. */

int main(void)
{
    unsigned int num         = 4000000;
    unsigned int big         = 2;
    unsigned int small       = 1;
    unsigned int tmpforsmall = 0;
    unsigned int sum         = big;
    
    while(big < 4000000){
        tmpforsmall = big;
        big         = big+small;
        small       = tmpforsmall;
        if(big % 2)
            continue;
        sum += big;
    }
    printf("%d\n",sum);
    return 0
}



