#include <stdio.h>

/* Each new term in the Fibonacci sequence is generated by adding the previous two terms. */
/*    By starting with 1 and 2, the first 10 terms will be: */
/*      1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...  */
/*          By considering the terms in the Fibonacci sequence whose values do not exceed four million, */
/*            find the sum of the even-valued terms.  */

#define MAX(a,b) ((a)>(b)?(a):(b))
#define MIN(a,b) ((a)<(b)?(a):(b))

static long long prarray[1000];

void make_parray(void)
{
    int i = 0;
    
    for(i=0;i<1000;i++)
        prarray[i]=0;


    
    

}



void main(void)
{



	/* unsigned long long int num   = 600851475143; */
    long long int num   = 600851475143;
    /* unsigned int big         = 2; */
    /* unsigned int small       = 1; */
    /* unsigned int tmpforsmall = 0; */
    /* unsigned int sum         = big; */
    unsigned long no = 1;
    
    int res = 0;

    make_parray();
    
    while(num--){
        if(num%2 == 0)continue;
        if(num%3 == 0)continue;
        if(num%5 == 0)continue;
        no=7;
        while( (no*no) < num  ){
            if(num%no == 0)break;
            num += 2;
        }
        if((no*no) >= num)break;
    }

    printf("fact no is %lld\n",num);
}



